name: 'Google chatroom message'
description: 'Send Google Chat messages for some github actions'
author: '@ipacheco'
branding:
  icon: 'send'
  color: 'blue'
inputs:
  url:
    description: 'Google Chat Webhook URL'
    required: true
  project:
    description: 'Jira project code (if issues are AA-105 then AA)'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
